[project]
name = "anaconda"
dependencies = [
    "flask >=3.0,<4",
    "markdown >=3.6,<4",
]
dynamic = ["version", "description"]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
