name: CI

on:
  - push
  - pull_request

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Dependencies
        run: python -m pip install -e '.[test]'

      - name: Run Linter
        run: flake8 anaconda


  pytest:
    runs-on: ubuntu-latest

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Dependencies
        run: python -m pip install -e '.[test]'

      - name: Run Unit Tests
        run: pytest .
